[package]
name = "iptr-perf-pt-reader"
version = "0.1.0"
edition = "2024"

[dependencies]
linux-perf-data = { workspace = true }
thiserror = { workspace = true }
derive_more = { workspace = true, features = ["display"] }
byteorder = { workspace = true }
