[package]
name = "iptr-perf-pt-reader"
description = "Perf.data parser for Intel PT data"
keywords = ["Intel PT", "perf", "perf.data"]
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lints]
workspace = true

[features]
default = []
std = []
memory_reader = [
  "dep:iptr-edge-analyzer",
  "dep:memmap2",
  "std",
] # Enable a reader implementing iptr_edge_analyzer::MemoryReader

[dependencies]
iptr-edge-analyzer = { workspace = true, optional = true }
memmap2 = { workspace = true, optional = true }
thiserror = { workspace = true }
derive_more = { workspace = true, features = ["display"] }
log = { workspace = true }
