[package]
name = "iptr-decoder"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
derive_more = { workspace = true, features = ["display"] }
memchr = { workspace = true }
perfect-derive = { workspace = true }
