[package]
name = "iptr-perf-pt-analyzer"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lints]
workspace = true

[dependencies]
iptr-decoder = { workspace = true, features = ["alloc"] }
iptr-edge-analyzer = { workspace = true }
iptr-perf-pt-reader = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
memmap2 = { workspace = true }
thiserror = { workspace = true }
